using System;
using SampleLibrary;
using NUnit.Framework;
using Moq;

namespace SampleLibrary.Tests
{
    class ClassATests
    {
        Mock<IDependency> _dependency;
        int _x;
        ClassA _classA;
        [SetUp]
        public void Setup()
        {
            _dependency = new Mock<IDependency>();
            _x = 0;
            _classA = new ClassA(_dependency.Object, _x);
        }

        [Test]
        public void Lie_Test()
        {
            bool result = _classA.Lie();
            bool expected = false;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Return3_Test()
        {
            int x = 0;
            int result = _classA.Return3(x);
            int expected = 0;
            Assert.That(result, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void SayTime_Test()
        {
            DateTime now = new System.DateTime();
            _classA.SayTime(now);
            Assert.Fail("autogenerated");
        }
    }
}